config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_host

  def set_host
    Rails.application.routes.default_url_options[:host] = request.host_with_port
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show

    if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(1)
    end

  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    if@book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
  end

  def find_book
    @book = Book.find(params[:id])
  end




end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end

  end

  def edit
  end

  def update

    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end

  end

  def find_review
    @review = Review.find(params[:id] )
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "カテゴリーを選んでください") %>
	<%= f.file_field :book_img %>
	<%= f.input :title, label: "本のタイトル" %>
	<%= f.input :description, label: "内容説明" %>
	<%= f.input :author, label: "著者" %>
	<%= f.button :submit, class: 'btn-custom2' %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-edit-form">

		<h1>本の編集</h1>

		<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
		　<%= f.select :category_id, @categories %>
			<%= f.file_field :book_img %>
			<%= f.input :title ,label: "タイトル" %>
			<%= f.input :description ,label: "内容" %>
			<%= f.input :author ,label: "著者" %>
			<%= f.button :submit, "本の追加" %>
		<% end %>

	</div>

</div>

app/views/books/index.html.erb
<h1 class="current_category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
  <h1>このカテゴリーの本はまだありません</h1>

<% else %>

  <div class="row">

    <% @books.each do |book| %>

      <div class="col-md-3">
        <a href="/books/<%= book.id %>">
          <%= image_tag book.book_img.url(:book_index), class: "book" %>
        </a>
      </div>

    <% end %>

  </div>
<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-book-form">
    <h1>新しい本</h1>

    <%= render 'form' %>

  </div>

</div>

app/views/books/show.html.erb
<div class="row">

  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: "book_show" %>
  </div>

  <div class="col-md-8">

    <div class="book-info">
      <h2 class="book-title"><%= @book.title %></h2>
      <h3 class="book-author"><span>著</span> <%= @book.author %></h3>
      <h3 class="avg-rating">平均評価</h3>
  		<h3><%= @average_review %></h3>
      <span class="number-of-reviews"><%= @book.reviews.count %>件のレビュー</span>
      <p class="book-description"><%= @book.description %></p>
    </div>

  </div>

</div>

<div class="row">

  <div class="col-md-4">

    <div class="reviews">
      <h1>レビュー</h1>
      <%= render @book.reviews %>

      <div>
        <%= link_to "レビューを追加する", new_book_review_path(@book), class: "btn btn-custom" %>
      </div>

    </div>

  </div>

</div>

<div class="links btn-group" >

  <%= link_to "戻る", root_path, class: "btn btn-custom" %>

    <% if user_signed_in? %>

  		<% if @book.user_id == current_user.id %>

  			<%= link_to "編集", edit_book_path(@book), class: "btn btn-custom" %>
  			<%= link_to "削除", book_path(@book), method: :delete, data: { confirm: "本当に消去しますか?" }, class: "btn btn-custom" %>

  	  <% end %>

   <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookreview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap -->
   <!-- <link href="Content/bootstrap.min.css" rel="stylesheet">
   <link href="Content/bootstrap-theme.min.css" rel="stylesheet"> -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
          <%= link_to "Bookmemo", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "無料で始める", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "サインアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
					 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">カテゴリー <span class="caret"></span></a>
					 <ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, books_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				  </li>


          <% if user_signed_in? %>
            <li><%= link_to "本を追加する", new_book_path %></li>
          <% end %>

        </ul>

      </div>

    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for( [@book, @book.reviews.build]) do |f| %>
  <%= f.input :rating, label: "５段階評価" %>
  <%= f.input :comment, label: "コメント" %>
  <%= f.button :submit, "レビューの作成", class: "btn-custom2" %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">

<p class="review-rating"><%= review.rating %></p>
<p class="review-comment"><%= review.comment %></p>

<% if user_signed_in? %>

  <% if review.user_id == current_user.id %>

    <div class="links btn group">

      <%= link_to "編集", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
      <%= link_to "削除", book_review_path(review.book, review), method: :delete, data: { confirm: "本当に削除してよろしいですか？" }, class: "btn btn-custom" %>

    </div>

  <% end %>

<% end %>

</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

    <h1>レビューの編集</h1>

    <%= simple_form_for([@book, @review]) do |f| %>
      <%= f.input :rating %>
      <%= f.input :comment %>
      <%= f.button :submit, class: "btn-custom2" %>
    <% end %>

  </div>

</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

    <h1>レビューの追加</h1>


    <%= render 'form' %>

  </div>

</div>